### PR TITLE
Add results of second tagging run

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by rootAvish** [comment]
Are you sure you want to store this here and not somewhere in S3?

**Comment by fridex** [comment]
> Are you sure you want to store this here and not somewhere in S3?

I don't mind - it's just temporary data that are good to have now. If you want I can upload them on S3.

**Comment by fridex** [comment]
>> Are you sure you want to store this here and not somewhere in S3?

> I don't mind - it's just temporary data that are good to have now. If you want I can upload them on S3.

Will do once credentials will be available.

**Comment by fridex** [comment]
> Will do once credentials will be available.

OK, having only read only access. @rootAvish Is this still relevant to merge or should I close this? These data are anyway just informative.

**Comment by rootAvish** [comment]
We can close it I guess. I have write access to S3 if you want me to upload it there.

**Comment by rootAvish** [comment]
Just tell me where it goes.

**Comment by fridex** [comment]
> Just tell me where it goes.

Wherever you find it suitable.

> We can close it I guess. I have write access to S3 if you want me to upload it there.

OK, feel free to use the file from this PR. Closing...

**Pull request closed without merging**
